### ISSUE TITLE
Please add license files to the test-generator crate

### ISSUE THREAD

**Issue by kalev** [frehberg/test-generator#15]
When packaging test-generator for Fedora it was noticed that the test-generator crate doesn't include license files. Please add them to the test-generator crate as well, similar to how they are already included in the build-deps and test-generator-udeps crates.

**Comment by frehberg** [comment]
I will do

**Comment by frehberg** [comment]
LICENSE files in package now and compiler warnings have been fixed

**Comment by kalev** [comment]
Excellent, thank you!
