### ISSUE TITLE
[Feature Request] Fail if no file is matched

### ISSUE THREAD

**Issue by demurgos** [frehberg/test-generator#4]
Thank you for your crate: it's very useful. While using it I encountered a common issue so I am submitting this feature request.

If the glob pattern does not match any file it is most likely an error: either the glob is invalid or the files are missing. If nothing is matched, it would be better to fail to compile. The current behavior (silently ignore the tests) could be provided as an opt-in.

**Comment by frehberg** [comment]
Thanks for the comment. Indeed, that would be useful. Maybe, do you have a patch at hand?

**Comment by demurgos** [comment]
I don't have a patch yet. When I get back to my Rust project, I may take a look if it's not available yet (I haven't looked into how this macro works internally).

**Comment by frehberg** [comment]
Just released 0.3, providing two new proc_macro_attributes `#[test_resources(GLOB_PATTERN)]` and  `#[bench_resources(GLOB_PATTERN)]`, old ones are deprecated.
These two new macros do fail, if the GLOB_PATTERN expands to empty list. Please use these two new macros,

**Comment by demurgos** [comment]
Thank you for the update. I appreciate the improvements.
